### PR TITLE
Fix: replace class side API implementation

### PR DESCRIPTION
**Pull request by guillep**
And some incompatible with Pharo12

### CODE REVIEW

**Comment by DurieuxPol** [comment]
Indeed I forgot to replace the class side API, thanks !
However the `aBloc millisecondsToRun` code doesn't seem to work in pharo 10.

**Comment by guillep** [comment]
Auch, true! It only works in Pharo 12!
And the thing is that the old API does not work in Pharo12!

I'll fix it :)

**Comment by DurieuxPol** [comment]
Maybe if we use `deprecated:transformWith:` instead of `deprecated:` for deprecated methods, it will work ?

**Comment by guillep** [comment]
That will rewrite users. We need a version that works for all Pharo versions.
There are not many solutions, and there are no magical ones ;)
- option 1: we choose our "good" api and provide a compatibility package that introduces it in the version it does not exist
- option 2: we add an if per version (if Pharo 12 we do this, otherwise we do that)
- option 3: we rely on a lower level API that is compatible but maybe not so nice to read

**Comment by guillep** [comment]
Now, since this is for a little method, I'm for option 2 :)

If we had incompatibilities in the compiler or some more complex stuff, or in something we use *a lot* then I would have a different opinion maybe.

**Comment by guillep** [comment]
Actually, there is `timeToRun` that is compatible in all pharo versions and returns a duration instead of an integer.
Which comes in handy because mutalk is taking the integer and converting it manually to a duration, so now there is no need for that. So Option 3ish it was!

**Comment by DurieuxPol** [comment]
Ok nice !
So everything works as intended now right ?

**Pull request merged**
